#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  6 15:39:41 2020

@author: samantha
"""

"""
Research Assignment 3:
    Topic: M33's Future Density Profile and Star Formation Rate
    
    Question 1: What can we infer about the SFR from the density profile? 
                Will there be a burst in star formation?

Equation to be used:
    fitting the stellar disk, use the surface density profile for disks:
    I(r) = I_0 * e^[-(r/h)^(1/n)]
    I_0 = central intensity
    h = scale length (radius at which intensity drops bt e-1)
    n = Sersic index 
    
Gurtina's suggestion on how to measure SFR:

    1) Determine the real M33 gas mass
        https://ui.adsabs.harvard.edu/abs/2009ApJ...703.1486P/abstract
        
        1.4e9 M_sun at the distance of 730pc. The dependency is M_HI 
        proportional to D**2, so using the largest M33 distance of 
        964 kpc all H1 regions should be multiplied by 1.7. So total gas
        mass is 2.38e9 M_sun. 

    2) Figure out the mass *ratio* between gas and stars
        Homework 3 gave the disk mass of M33 to be 0.009e12 Msun, and the total
        mass to be 0.196e12 M_sun.
        ratio between gas and stars = gas / stars = gas / disk mass 
        (M33 doesn't have a bulge)
        ratio = 2.38e9 / 0.009e12 = 0.264

    3) make plots of the surface density of stars in M33 
        (mass/area as a function of radius).  Translate that into gas surface 
        density using the ratio between gas and stars from #2 

    4) Use the Kennicutt Schmidt relation to translate the gas density into a 
        star formation rate. 
         \Sigma_{SFR} = (2.5 \pm{0.7}) \times 10^{-4} (\frac{\Sigma_{gas}}{1 M_{sun} pc^{-2}})^{1.4 \pm{0.15}} M_{sun} yr^{-1} kpc^{-2}
         
         or
         
         \Sigma_{SFR} = A \Sigma_{gas}^N, 
             \Sigma_{gas}: surface density of gas
             A: the absolute SFR efficiency
             N: most values fall in the range 1-2 depending on tracers and 
             the linear scales considered
         From Kennicutt 1997: https://arxiv.org/abs/astro-ph/9712213

    5)[ if you have time ] 
        You can even then use that star formation rate at each point in the 
        orbit to decrease the gas mass at each point in time and determine 
        when you think all the gas would be used up by. 
    
Methods:
    => Similar to Lab 6: 
        create a function to calculate the surface density profile for disks
        n = 1 for spiral galaxies --> M33 is currently a gas rich late type 
        spiral that could evolved into a gas poor spiral or elliptial once
        M31 and MW collide. n = 4 for ellipical galaxies
        
        also make stellar disk density profile as a function of time??
        
    => translate into gas surface density
    
    => translate the gas surface density into a SFR
    
    => determine when gas would be used up
    
"""

# Surface Brightness Profiles

# Load Modules
import numpy as np
import astropy.units as u

# import plotting modules
import matplotlib.pyplot as plt
import matplotlib

# my modules
from ReadFile import Read
from CenterOfMass import CenterOfMass
from MassProfile import MassProfile


# # From Lab 6: Sersic Profiles
# 
# In this lab we used Homework 5 solutions to compute the mass profile of M31's bulge. 
# We turned the mass profile into a density profile and saw if we can fit it reasonably well 
# with a sersic profile. 

# # Part A : 
# 
# Create a function called `SersicS` that returns the Sersic Profile 

# We will assume a mass to light ratio for the stellar bulge of 1
# 

#give an array of radii
#function to return Sersic profile for a spiral system
def SersicS(R, h, n, Mtot):
    #Inputs:
    #   R: array of radii [kpc]
    #   h: scalelength (radius at which intensity drops by e-1)
    #   n: Sersic index
    #   Mtot, total stellar mass [Msun]
    #Return:
    #   surface brightness profile [Lsun/kpc^2]
    #asuume M/L = 1
    L = Mtot #total luminosity = total stellar mass
    
    # L = pi * I0 * h^2 (2n)!
    # solving for I0
    I0 = L/np.pi/h**2/np.math.factorial(2*n)
    #exponent
    A = (R/h)**(1/n)
    
    return I0*np.exp(-A)



# # Part B
# 
# Compute the surface density profile for the simulated disk
# 
# a) Create an instance of the MassProfile Class for M33. Store it as a variable `M33`. 
# 
M33 = MassProfile("M33", 0)

# b) Create an array of radii from 0.1 kpc to 30 kpc in increments of 0.1
# 
R = np.arange(0.1, 15, 0.1)
DiskMass = M33.MassEnclosed(2, R)  #particle type 2 = disk
print(DiskMass[10])

# c) Define a new array called `DiskMass`, that uses the function `MassEnclosed` 
#   within MassProfile to compute the mass profile of the disk. 
# Get rid of astropy units in `DiskMass` by adding `.value` 
# I = L / 4 pi D^2
DiskI = DiskMass/(np.pi*R**2)

# d) Compute the surface mass density profile for the simulated disk
# store it as an array called `DiskI`. 
# Assuming M/L ~ 1 this is also the surface brightness profile in Lsun/kpc^2


DiskTotal = np.max(DiskMass) #total mass of bulge
print(DiskTotal)


# # Part D
# 
# a) Plot the surface density profile of the simulated disk
# 
# b) Plot the Sersic profile, assuming an exponential for spiral


# Plot the Disk density profile vs 
# the Sersic profile
####################################


fig = plt.figure(figsize=(5,5))
ax = plt.subplot(111)


# plot the disk luminosity density as a proxy for surface brighntess
# x-axis = array of radii
# y - axis = density of disk in terms of luminosity 
plt.semilogy(R,DiskI, color='blue',linewidth=3, label='Disk Density')

# multiply by ratio found in step two to get gas density profile
#### Not sure if I did this right ###
# gas / stars = 0.264
# y-axis is now the mass * gas to mass ratio / area of a disk
plt.semilogy(R,DiskI*0.264, color='orange',linewidth=3, label='Gas Density')

# plot using density function from Miyamoto and Nagai
# Rixin's method of plotting ?

# translate gas density to SF density using the Kennicutt Schmidt relation to 
#   translate the gas density into a star formation rate. 
#   \Sigma_{SFR} = (2.5 \pm{0.7}) \times 10^{-4} (\frac{\Sigma_{gas}}{1 M_{sun} pc^{-2}})^{1.4 \pm{0.15}} M_{sun} yr^{-1} kpc^{-2}

### not sure what to plot here ###
# Units seem off???      
SFD = 2.5*10**(-4)*(DiskI[-1]*0.264)**1.4 # M_sun yr^-1 kpc^-2
print("SFD =",SFD)
print("gas density", DiskI[-1]*0.264)

SFR = SFD*R[-1]
print("SFR =",SFR)

# YOU ADD HERE: Sersic fit to the surface brightness Sersic fit
# Sersic 
#plt.semilogy(R, SersicS(R, h, 1, DiskTotal), color = 'red', linestyle = "-.", Linewidth = 3, label = 'Sersic n = 1')


#adjust tick label font size
label_size = 22
matplotlib.rcParams['xtick.labelsize'] = label_size 
matplotlib.rcParams['ytick.labelsize'] = label_size


# Add axis labels
plt.xlabel('Radius (kpc)', fontsize=22)
plt.ylabel('Log(I)  $L_\odot/kpc^2$', fontsize=22)



# add a legend with some customizations.
legend = ax.legend(loc='upper right',fontsize='x-large')

plt.show()

### Plot M33 wrt M31 and mark close encounters ###
# from lab 11 but flipped to agree with above statement






